---
#
- name: prepare installation response file
  template:
    src: wls-install-12c.rsp.j2
    dest: "{{ oracle_weblogic_response_file }}"
  when: not oracle_weblogic_quick_installation

- set_fact:
    oracle_weblogic_install_command: "java -jar {{ oracle_weblogic_jar }} ORACLE_HOME={{ oracle_weblogic_oracle_home }} >> /tmp/weblogic-installation.log"
  when: oracle_weblogic_quick_installation

- set_fact:
    oracle_weblogic_install_command: "java -jar {{ oracle_weblogic_jar }} -silent -responseFile {{ oracle_weblogic_response_file }} >> /tmp/weblogic-installation.log"
  when: not oracle_weblogic_quick_installation

- name: install weblogic
  shell: "{{ oracle_weblogic_install_command }}"
  args:
    creates: "{{ oracle_weblogic_oracle_home }}/oraInst.loc"
